apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation

metadata:
  name: vets-service-automation
  namespace: flux-system

spec:
  interval: 1m

  sourceRef:
    kind: GitRepository
    name: petclinic-gitops

  git:
    checkout:
      ref:
        branch: main

    commit:
      author:
        name: flux-bot
        email: flux@example.com

      messageTemplate: |
        Update vets-service image

    push:
      branch: main

  update:
    path: ./
    strategy: Setters