apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Release.Name } }
  labels:
    app: config-server

spec:
  replicas: { { .Values.replicaCount } }

  selector:
    matchLabels:
      app: config-server

  template:
    metadata:
      labels:
        app: config-server

    spec:
      containers:
        - name: config-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }

          ports:
            - containerPort: { { .Values.containerPort } }

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 40
            periodSeconds: 20
            failureThreshold: 5
