replicaCount: 1
image:
  repository: alihamza9/petclinic-discovery-server
  tag: "6ceba5585f892064dcb5b62fd7ade8bfbcfecaf2" # {"$imagepolicy": "flux-system:discovery-server-policy:tag"}
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8761
containerPort: 8761
