apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api-gateway
  namespace: petclinic
spec:
  interval: 5m
  chart:
    spec:
      chart: ./apps/api-gateway
      sourceRef:
        kind: GitRepository
        name: petclinic-gitops
        namespace: flux-system