apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: discovery-server
  namespace: petclinic

spec:
  interval: 5m

  chart:
    spec:
      chart: ./apps/discovery-server

      sourceRef:
        kind: GitRepository
        name: petclinic-gitops
        namespace: flux-system
