apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Helm releases
  - config-server-helmrelease.yaml
  - discovery-server-helmrelease.yaml
  - customers-service-helmrelease.yaml
  - visits-service-helmrelease.yaml   
  - vets-service-helmrelease.yaml
  # Image Resources
  - ../../infrastructure/flux/image-repositories/config-server-repo.yaml
  - ../../infrastructure/flux/image-repositories/config-server-policy.yaml
  - ../../infrastructure/flux/image-automation/config-server-automation.yaml
  - ../../infrastructure/flux/image-repositories/discovery-server-repo.yaml
  - ../../infrastructure/flux/image-repositories/discovery-server-policy.yaml
  - ../../infrastructure/flux/image-automation/discovery-server-automation.yaml
  - ../../infrastructure/flux/image-repositories/customers-service-repo.yaml
  - ../../infrastructure/flux/image-repositories/customers-service-policy.yaml
  - ../../infrastructure/flux/image-automation/customers-service-automation.yaml
  - ../../infrastructure/flux/image-repositories/visits-service-repo.yaml
  - ../../infrastructure/flux/image-repositories/visits-service-policy.yaml
  - ../../infrastructure/flux/image-automation/visits-service-automation.yaml
  - ../../infrastructure/flux/image-repositories/vets-service-repo.yaml
  - ../../infrastructure/flux/image-repositories/vets-service-policy.yaml
  - ../../infrastructure/flux/image-automation/vets-service-automation.yaml