apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Helm releases
  - config-server-helmrelease.yaml
  - discovery-server-helmrelease.yaml
  - customers-service-helmrelease.yaml
  - visits-service-helmrelease.yaml   
  - vets-service-helmrelease.yaml