apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vets-service
  namespace: petclinic
spec:
  interval: 5m
  chart:
    spec:
      chart: ./apps/vets-service
      reconcileStrategy: Revision
      
      sourceRef:
        kind: GitRepository
        name: petclinic-gitops
        namespace: flux-system