replicaCount: 1
image:
  repository: alihamza9/petclinic-customers-service
  tag: "2b7caf60a7211bead140d7217b57c11aab1bcfbe" # {"$imagepolicy": "flux-system:customers-service-policy:tag"}
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8081
containerPort: 8081
config:
  SPRING_PROFILES_ACTIVE: docker
  CONFIG_SERVER_URL: http://config-server:8888
  EUREKA_SERVER_URL: http://discovery-server:8761/eureka/
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql.petclinic.svc.cluster.local:3306/customersdb
  SPRING_DATASOURCE_USERNAME: petclinic
  SPRING_DATASOURCE_PASSWORD: petclinic123

  SPRING_JPA_HIBERNATE_DDL_AUTO: update
