apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}
  labels:
    app: discovery-server

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: discovery-server

  template:
    metadata:
      labels:
        app: discovery-server

    spec:
      containers:
        - name: discovery-server

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

        
            periodSeconds: 20
            timeoutSeconds: 10
