apiVersion: v1
kind: Service

metadata:
  name: { { .Release.Name } }

  labels:
    app: discovery-server

spec:
  type: { { .Values.service.type } }

  selector:
    app: discovery-server

  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.containerPort } }
