apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - name: visits-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: CONFIG_SERVER_URL
              value: {{ .Values.env.CONFIG_SERVER_URL | quote }}
            - name: MYSQL_HOST
              value: {{ .Values.env.MYSQL_HOST | quote }}
            - name: MYSQL_PORT
              value: {{ .Values.env.MYSQL_PORT | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.env.MYSQL_DATABASE | quote }}
            - name: MYSQL_USERNAME
              value: {{ .Values.env.MYSQL_USERNAME | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.env.MYSQL_PASSWORD | quote }}