apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-services
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - petclinic
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  endpoints:
    - path: /actuator/prometheus
      port: http
      interval: 15s
