apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}

            - name: CONFIG_SERVER_URL
              value: {{ .Values.env.CONFIG_SERVER_URL | quote }}

            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.SPRING_DATASOURCE_URL | quote }}

            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.SPRING_DATASOURCE_USERNAME | quote }}

            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.env.SPRING_DATASOURCE_PASSWORD | quote }}

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: {{ .Values.env.SPRING_JPA_HIBERNATE_DDL_AUTO | default "update" | quote }}

            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "1.0"
              
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tempo.monitoring.svc.cluster.local:9411/api/v2/spans"