replicaCount: 1
image:
  repository: alihamza9/petclinic-config-server
  tag: "c3b04838e44ecf6ba17828e6b0b94fb54444eb43" # {"$imagepolicy": "flux-system:config-server-policy:tag"}
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8888
containerPort: 8888

env:
  - name: SPRING_PROFILES_ACTIVE
    value: git

  - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
    value: https://github.com/spring-petclinic/spring-petclinic-microservices-config

  - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
    value: main

  - name: SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START
    value: "true"
