replicaCount: 1
image:
  repository: alihamza9/petclinic-config-server
  tag: "dummy" # {"$imagepolicy": "flux-system:config-server-policy:tag"}
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8888
containerPort: 8888
