replicaCount: 1
image:
  repository: alihamza9/petclinic-config-server
  tag: "alihamza9/petclinic-config-server:c3b04838e44ecf6ba17828e6b0b94fb54444eb43" # {"$imagepolicy": "flux-system:config-server-policy"}
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8888
containerPort: 8888
