apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: petclinic-gitops
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/petclinic-sdlc/gitops
  ref:
    branch: main
  secretRef:
    name: github-auth
