tempo:
  retention: 6h

  structuredConfig:
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        zipkin:
          protocols:
            http:
              endpoint: 0.0.0.0:9411

    ingester: {}

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces

    querier: {}
    query_frontend: {}

persistence:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi