tempo:
  retention: 6h
  extraArgs:
    config.expand-env: true
  structuredConfig:
    receivers:
      zipkin:
        enabled: true 
        protocols:
          http: {}

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces

    distributor:
      receivers:
        zipkin:

persistence:
  enabled: false

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi