tempo:
  repository: grafana/tempo
  tag: 2.9.0

multitenancyEnabled: false

tempoQuery:
  enabled: false

persistence:
  enabled: false

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi

config: |
  server:
    http_listen_port: 3200

  distributor:
    receivers:
      zipkin:
        protocols:
          http:
            endpoint: 0.0.0.0:9411

  ingester:
    trace_idle_period: 10s
    max_block_duration: 5m

  compactor:
    compaction:
      block_retention: 6h

  storage:
    trace:
      backend: local
      local:
        path: /tmp/tempo/traces
      wal:
        path: /tmp/tempo/wal

  querier: {}

  query_frontend: {}